# Generated by Django 4.1.2 on 2024-10-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='precio_producto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
