# Generated by Django 4.1.2 on 2024-10-13 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_productos_precio_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('testcamp', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='productos',
            name='imagen_producto',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
